Feature branch for  website
arslanbisharat/resturant-page pull request #1
Opened 2020-07-04 00:39 UTC by arslanbisharat

### resturant-page
**I used JavaScript alone to generate the entire contents of the website!**
> Readme has enough information to run this repo
>It has three main section About, menu and location
> location is  not workng right  now.

2020-07-05 13:09 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,

Thank you for this well done job.
Before merging, please read the comments below and submit a new code review request
Also, include `.vscode` into `.gitignore`.

Thanks

Mael FOOSO

2020-07-05 13:09 UTC, maelfosso commented on src/food.js
> +    const productsUrls = ['images/HalwaPuri.jpeg', 'images/Biryani.jpeg', 'images/Chicken.jpeg', 'images/Lassi.jpg', 'images/Drinks.jpg', 'images/dessert.jpeg']
![Screenshot at 2020-07-05 14:04:17](https://user-images.githubusercontent.com/8848104/86533368-8f971000-bec8-11ea-9717-94cb5ee06e4d.png)
This error is due to the wrong name of images. Kindly fix it.

2020-07-05 13:09 UTC, maelfosso commented on src/about_us.js
> +}
Make your code more readable.
Indent it correctly. Update also the others files, please.

2020-07-06 15:40 UTC, fatymahmed approved these changes
## Hi @arslanbisharat,
Great job making the requested changes 🎉🎉
Please make the following change before merging.
- Make sure to update `dist/main.js` with the latest changes you made

[OPTIONAL]
- Set up linter, [here's](https://github.com/microverseinc/linters-config/tree/master/javascript) how to do so
## Status: Approved ✔️

2020-07-27 04:12 UTC, merged